### ISSUE TITLE
Add Xbox Controller support

### ISSUE THREAD

**Issue by BenjaminFaal** [BenjaminFaal/TwoPlayerMod#1]
By preference add support for it with the SharpDX.XInput library.

**Comment by BenjaminFaal** [comment]
Im at the point of the mod recognizing the Xbox controller input but gta v is taking over and this means that it will also control player1. Now I just need a way to disable that.

**Comment by The12GaugeGroove** [comment]
I will clarify before I begin, I absolutely love the script and wish nothing but the best for it, and having been playing it from the beginning I'm very impressed with the progress presented so far. What is below may seem harsh, but it is in no way intended to be, as I only write here with the hopes that these issues won't be overlooked amongst the floods of morons on GTA5-Mods who can't figure out how to install base modules for running scripts properly.

As of version 1.3, driving functionality for player 2 (controller ped) has improved significantly. My friends and I have had an absolute blast playing with this already, however:

Two controllers are still needed for the mod to function properly, the first controller made to sit somewhere unused while player two uses the second controller (which, if the user has set up his scripts properly, should work). Player 1 at this time may only use the keyboard, leaving the first-player controller untouched (as it will cause whoever uses it to control both on-screen characters at once). The controller PC driver provided with 1.3's download didn't seem to do much to fix this either, despite Benjamin's good intentions.

Unfortunately, on-foot movement for player 2 is still hardly functioning, with mostly severe delays and miscommunication between joystick input and which direction the pedestrian player 2 controls walks in. A debug feature that prompted player 2 to slide forward with no animation (but still at a faster pace than walking) using A has been removed as well, making the already near-impossible task of simple on-foot movement even harder because now player 2 must time a jump in a direction and spam it that way, as the constantly-spinning pedestrian he controls doesn't really decide on much besides small circles, even with analog input.

Driving for player 2 has improved dramatically since earlier versions, but there is still minor controller response hiccups and delays that may prove to be hazardous if you give your friend the wheel and expect them to drive professionally. Still, parallel parking and other such driving feats are definitely possible in its current state, but it still feels a little unresponsive at points and the steering likes to lock up left or right at random. It can ruin a lot of fun moments but it's still far-better than any previous version of the script.

Combat availabilities for player 2 (besides running people over) are nonexistent as well, presumably due to the major task of implementing such a system into the game for a separate player to utilize as well.. Maybe there could be a way for player 2 to force his ped into a "combat" mode of some sort? Something like a quick AI behavior that essentially turns the player 2 pedestrian into an AI bodyguard that protects and fights alongside player 1 until the mode is turned off? Maybe another similar mode that just makes them attack whatever target entity is specified beforehand? I'm no tech wizard so i don't really know what is possible, and it wouldn't be perfect, but at least player 2 could have some sort of fighting chance this way or one similar, because if they're backed into a corner against some angry gangsters, they will endlessly get their ass beat.

Camera. Of course split-screen isn't possible so I won't even daunt you with the task. However, perhaps a way to zoom player 1's camera out much further than usual and lock it in an isometric-type view may work better? For example, watch this video to see how Rockstar themselves did it in GTA: San Andreas. Again, I'm not tech-savvy such as the developer, but a system like this seems much more doable compared to actual split-screen (which in itself goes against all of the core RAGE engine's rendering possibilities): https://www.youtube.com/watch?v=3HEY1svFQIA&t=75

Thank you for taking the time to look into these, as I hope they're not missed among the waves of dumb shit people like giving you in your comments section. I eagerly await future progress and wish you the best of luck!

**Comment by BenjaminFaal** [comment]
Hey man thanks you seem to understand it correctly! Please open a new issue on this github for each issue. So I can report correctly to all issues and fix them one by one.
